version: '3.8'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes: 
            - ./nginx:/usr/share/nginx/html
    mysql: 
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=testdb
        ports:
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - "8082:80"
        depends_on:
            - mysql
    web2:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8083:80"

       
