version: '3.8'
services:
    Redis:
        image: redis:6
        ports:
            - "6379:80"
    web: 
        image: python:3.9-slim
        volumes: 
            - ./app:/usr/src/app
        ports:
            - "5000:5000"
        depends_on:
            - Redis

    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER= user
            - POSTGRES_PASSWORD= password
            - POSTGRES_DB= mydatabase
        ports:
            - "5432:5432"
    nginx:
        image: nginx
        ports:
            - "80:80"
        
        depends_on:
            - web

       
