version: '3.8'
services:
    Redis:
        image: redis:6
        ports:
            - "6379:6379"
    web: 
        volumes: 
            - ./app:/usr/src/app
        ports:
            - "5000:5000"
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app 
        depends_on:
        - Redis 
        - db




    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER= user
            - POSTGRES_PASSWORD= password
            - POSTGRES_DB= mydatabase
        ports:
            - "5432:5432"
        volumes: 
            - ./data:/var/lib/postgresql/data
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web

       
